### PR TITLE
ARCHER2 fixes from MOSRS (includes all changes)

### PR DESCRIPTION
**Pull request by leifdenby**
This pull-request represents all changes on branches/dev/adrianhill/r8166_archer2_fix on MOSRS relative to our master branch

### CODE REVIEW

**Comment by leifdenby** [comment]
The good news is that this compiles and runs in single-core ubuntu (CI test passed). The challenge is that it includes many more things besides just fixes for ARCHER2 (because this was branched from `trunk` on MOSRS and not from a tagged version). I will need to go through and find the changes that we need.

**Comment by cemac-ccs** [comment]
Am I right in thinking that the first commit in this list comprises all the Reading changes to bring Leeds-MONC level with the HEAD of MOSRS and so can be ignored for the time being (with the obvious exception of where the archer2 changes and Reading changes intersect)?

**Comment by cemac-ccs** [comment]
Have gone through the commits, and if numbering the list of commits on this ticket from the top then the list of commits which are needed to run the Leeds branch without casim or socrates on Archer2 are commits 3,4,5,7 and 10. Commit 1 seems to be the Reading mega-change, commit 2 is changes to code that only exists on the trunk or if commit 1 has been merged in. Parts of commits 4 and 8 may be needed and I am unsure of commit 9 - more testing with casim and socrates will hopefully shed light on this.

I expect to have a PR ready for review soon once I have tried running bomex with casim, socrates and both casim and socrates.

**Comment by leifdenby** [comment]
I'm closing this because it is being superseded by https://github.com/Leeds-MONC/monc/pull/45

**Pull request closed without merging**
