### PR TITLE
Add "how to contribute" to README

### PR DESCRIPTION
**Pull request by leifdenby**
As my first pull-request I'm adding some notes to the README about how to contribute, please let me know what you think 😄 thank you

Link to the notes rendered on github:
https://github.com/leifdenby/monc/tree/readme-how-to-contribute#contributing

### CODE REVIEW

**Review by gymccusker — APPROVED** [review]

**Comment by MarkUoLeeds** [comment]
A space missing in sourcecode ? Or leave it as sourcecode.

**Review by MarkUoLeeds — APPROVED** [review]

**Review by leosaffin — APPROVED** [review]
Looks good to me. Concise and complete

**Comment by craigpoku** [comment]
Could I suggest that you link this guide on github: https://guides.github.com/activities/hello-world/

Sometimes it pops up and other times it doesn't. But in case someone misses it, it just makes the idea of using git more approachable.

Also, I know that @gyoung410 mentioned to me a specific word editor that works well with github. I can't remember what it was, but it may be worth recommending it in the readme?

**Review by craigpoku — COMMENTED** [review]
Could I suggest that you link this guide on github: https://guides.github.com/activities/hello-world/

Sometimes it pops up and other times it doesn't. But in case someone misses it, it just makes the idea of using git more approachable.

Also, I know that @gyoung410  mentioned to me a specific word editor that works well with github. I can't remember what it was, but it may be worth recommending it in the readme?

**Comment by gymccusker** [comment]
I use Atom, it's very easy to link it to your Github account and makes commits a bit easier (in my opinion!). Could mention it, might not be to everyone's taste but I suppose it provides the option to those who are unfamiliar.

**Comment by craigpoku** [comment]
> I use Atom, it's very easy to link it to your Github account and makes commits a bit easier (in my opinion!). Could mention it, might not be to everyone's taste but I suppose it provides the option to those who are unfamiliar.

In that case, we could add it as an example github editor in the readme. 

I'm mostly thinking about this readme from the complete beginner's perspective btw

**Comment by leifdenby** [comment]
> Could I suggest that you link this guide on github: https://guides.github.com/activities/hello-world/

Yup, I can add that in. It doesn't mention making a your own "fork" and working of that though, so it's more geared to when you're not working together with others I think. I can try look for a different guide which mentions forks if you think that will be helpful.

**Review by sjboeing — APPROVED** [review]

**Comment by craigpoku** [comment]
> > Could I suggest that you link this guide on github: https://guides.github.com/activities/hello-world/
> 
> Yup, I can add that in. It doesn't mention making a your own "fork" and working of that though, so it's more geared to when you're not working together with others I think. I can try look for a different guide which mentions forks if you think that will be helpful.

Like this? https://guides.github.com/activities/forking/

**Review by MarkUoLeeds — APPROVED** [review]

**Comment by leifdenby** [comment]
Thanks all!

**Pull request merged**
